### PR TITLE
Very rough stab at scaling

### LINKED ISSUE #2: Implement automatic scaling factor
Currently hardcoded to 1

### PR DESCRIPTION
**Pull request by patricia-gallardo**
Doesn't fix #2 properly yet

### CODE REVIEW

**Comment by patricia-gallardo** [comment]
Needs serious prettification

**Comment by cor3ntin** [comment]
Thanks for doing that <3
I wonder if we should do it the other way around though.
I think what we have no on windows is the size that we want visually on all systems. So that scale should be one.
And the image should still be `/2` - because the asset file is basically double resolution.
Does that make sense?

**Comment by patricia-gallardo** [comment]
For me it ended up the other way in my mind - the sprites are the right size and the maze is the wrong size

**Comment by cor3ntin** [comment]
The maze is interesting because if we try to render it at twice the resolution on mac it might look weird. I guess we need to try?

**Comment by patricia-gallardo** [comment]
I tried and it looks fine, its pixelated but that is how it is so it scales well

**Pull request merged**
